spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/explore_app
spring.datasource.username=explore_user
spring.datasource.password=explore_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health