CREATE TABLE users (
    id UUID PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(150) NOT NULL,
    role VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'MANAGER', 'USER')),
    CONSTRAINT users_status_check CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_users_email ON users (email);

CREATE TABLE locations (
    id BIGINT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    point geography(Point, 4326),
    county VARCHAR(255),
    category VARCHAR(255),
    experience INTEGER,
    difficulty INTEGER,
    notes TEXT,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT locations_status_check CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE journeys (
    id BIGINT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    county VARCHAR(255),
    category VARCHAR(255),
    experience INTEGER,
    distance DOUBLE PRECISION,
    difficulty INTEGER,
    polyline TEXT,
    notes TEXT,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT journeys_status_check CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE journey_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journey_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT uk_journey_location UNIQUE (journey_id, location_id),
    CONSTRAINT fk_journey_locations_journey
        FOREIGN KEY (journey_id) REFERENCES journeys (id) ON DELETE CASCADE,
    CONSTRAINT fk_journey_locations_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
);

CREATE INDEX idx_journey_locations_journey_id_sort_order
    ON journey_locations (journey_id, sort_order);

CREATE TABLE location_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL,
    image_url TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT fk_location_images_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
);

CREATE INDEX idx_location_images_location_id
    ON location_images (location_id);

CREATE INDEX idx_location_images_location_id_sort_order
    ON location_images (location_id, sort_order);
