DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'locations'
    ) THEN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'location_images'
        ) THEN
            CREATE TABLE location_images (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                location_id BIGINT NOT NULL,
                image_url TEXT NOT NULL,
                sort_order INTEGER NOT NULL,
                CONSTRAINT fk_location_images_location
                    FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
            );
        END IF;

        CREATE INDEX IF NOT EXISTS idx_location_images_location_id
            ON location_images (location_id);

        CREATE INDEX IF NOT EXISTS idx_location_images_location_id_sort_order
            ON location_images (location_id, sort_order);

        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'locations'
              AND column_name = 'image_url'
        ) THEN
            INSERT INTO location_images (location_id, image_url, sort_order)
            SELECT
                l.id,
                l.image_url,
                COALESCE((
                    SELECT MAX(li.sort_order) + 1
                    FROM location_images li
                    WHERE li.location_id = l.id
                ), 0)
            FROM locations l
            WHERE l.image_url IS NOT NULL
              AND BTRIM(l.image_url) <> ''
              AND NOT EXISTS (
                  SELECT 1
                  FROM location_images li
                  WHERE li.location_id = l.id
                    AND li.image_url = l.image_url
              );

            ALTER TABLE locations DROP COLUMN image_url;
        END IF;
    END IF;
END $$;
