CREATE TABLE location_discoveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    location_id BIGINT NOT NULL,
    discovered_at TIMESTAMPTZ NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    accuracy_meters DOUBLE PRECISION,
    distance_meters DOUBLE PRECISION,
    source VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_location_discovery_user_location UNIQUE (user_id, location_id),
    CONSTRAINT fk_location_discoveries_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_location_discoveries_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE,
    CONSTRAINT location_discoveries_source_check
        CHECK (source IN ('GPS', 'MANUAL_ADMIN', 'SYNCED_OFFLINE'))
);

CREATE INDEX idx_location_discoveries_user_id
    ON location_discoveries (user_id);

CREATE INDEX idx_location_discoveries_location_id
    ON location_discoveries (location_id);

CREATE TABLE journey_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    journey_id BIGINT NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_journey_completion_user_journey UNIQUE (user_id, journey_id),
    CONSTRAINT fk_journey_completions_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_journey_completions_journey
        FOREIGN KEY (journey_id) REFERENCES journeys (id) ON DELETE CASCADE
);

CREATE INDEX idx_journey_completions_user_id
    ON journey_completions (user_id);

CREATE INDEX idx_journey_completions_journey_id
    ON journey_completions (journey_id);
