CREATE TABLE trip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_trip_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_trip_user_updated_at
    ON trip (user_id, updated_at DESC);

CREATE TABLE trip_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_trip_location UNIQUE (trip_id, location_id),
    CONSTRAINT fk_trip_location_trip
        FOREIGN KEY (trip_id) REFERENCES trip (id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_location_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
);

CREATE INDEX idx_trip_location_trip_sort_order
    ON trip_location (trip_id, sort_order ASC);

CREATE TABLE trip_journey (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    journey_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_trip_journey UNIQUE (trip_id, journey_id),
    CONSTRAINT fk_trip_journey_trip
        FOREIGN KEY (trip_id) REFERENCES trip (id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_journey_journey
        FOREIGN KEY (journey_id) REFERENCES journeys (id) ON DELETE CASCADE
);

CREATE INDEX idx_trip_journey_trip_sort_order
    ON trip_journey (trip_id, sort_order ASC);
